LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := curve25519
LOCAL_CURVE25519_SRC := $(LOCAL_PATH)/../src/
LOCAL_C_INCLUDES := $(LOCAL_CURVE25519_SRC)/

LOCAL_SRC_FILES := \
$(LOCAL_CURVE25519_SRC)/curve25519-donna.c

include $(BUILD_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := curve25519-lockateme
LOCAL_STATIC_LIBRARIES := curve25519

LOCAL_CURVE25519_SRC := $(LOCAL_PATH)/../src/
LOCAL_C_INCLUDES := $(LOCAL_CURVE25519_SRC)

# LOCAL_LOCKATEME_SRC := $(LOCAL_PATH)
LOCAL_SRC_FILES := $(LOCAL_PATH)/curve25519-jni.c

LOCAL_LDLIBS := -llog

include $(BUILD_SHARED_LIBRARY)
